"use client";

import { useState, useEffect } from "react";

export function RandomData(data: Array<any>) {
  const [randomData, setRandomData] = useState(""); // Default emoji or loading indicator
  const [loading, setLoading] = useState(true); // State to track if data is being fetched

  useEffect(() => {
    const fetchRandomEmoji = async () => {
      try {
        // Simulate fetching from an API or generating a random emoji
        const fetchedEmoji = data[Math.floor(Math.random() * data.length)];
        setRandomData(fetchedEmoji);
      } catch (error) {
        console.error("Error fetching random data:", error);
      } finally {
        setLoading(false); // Mark loading as done regardless of success or failure
      }
    };

    fetchRandomEmoji();
  }, []); // Empty dependency array to run this effect only once on mount

  if (loading) {
    return <span>Loading...</span>; // Display a loading state while fetching the emoji
  }

  return <span>{randomData}</span>; // Render the fetched emoji when available
}

export function RandomEmoji() {
  var emojis = [
    "😄",
    "😃",
    "😀",
    "😊",
    "☺",
    "😉",
    "😍",
    "😘",
    "😚",
    "😗",
    "😙",
    "😜",
    "😝",
    "😛",
    "😳",
    "😁",
    "😔",
    "😌",
    "😒",
    "😞",
    "😣",
    "😢",
    "😂",
    "😭",
    "😪",
    "😥",
    "😰",
    "😅",
    "😓",
    "😩",
    "😫",
    "😨",
    "😱",
    "😠",
    "😡",
    "😤",
    "😖",
    "😆",
    "😋",
    "😷",
    "😎",
    "😴",
    "😵",
    "😲",
    "😟",
    "😦",
    "😧",
    "😈",
    "👿",
    "😮",
    "😬",
    "😐",
    "😕",
    "😯",
    "😶",
    "😇",
    "😏",
    "😑",
    "👲",
    "👳",
    "👮",
    "👷",
    "💂",
    "👶",
    "👦",
    "👧",
    "👨",
    "👩",
    "👴",
    "👵",
    "👱",
    "👼",
    "👸",
    "😺",
    "😸",
    "😻",
    "😽",
    "😼",
    "🙀",
    "😿",
    "😹",
    "😾",
    "👹",
    "👺",
    "🙈",
    "🙉",
    "🙊",
    "💀",
    "👽",
    "💩",
    "🔥",
    "✨",
    "🌟",
    "💫",
    "💥",
    "💢",
    "💦",
    "💧",
    "💤",
    "💨",
    "👂",
    "👀",
    "👃",
    "👅",
    "👄",
    "👍",
    "👎",
    "👌",
    "👊",
    "✊",
    "✌",
    "👋",
    "✋",
    "👐",
    "👆",
    "👇",
    "👉",
    "👈",
    "🙌",
    "🙏",
    "☝",
    "👏",
    "💪",
    "🚶",
    "🏃",
    "💃",
    "👫",
    "👪",
    "👬",
    "👭",
    "💏",
    "💑",
    "👯",
    "🙆",
    "🙅",
    "💁",
    "🙋",
    "💆",
    "💇",
    "💅",
    "👰",
    "🙎",
    "🙍",
    "🙇",
    "🎩",
    "👑",
    "👒",
    "👟",
    "👞",
    "👡",
    "👠",
    "👢",
    "👕",
    "👔",
    "👚",
    "👗",
    "🎽",
    "👖",
    "👘",
    "👙",
    "💼",
    "👜",
    "👝",
    "👛",
    "👓",
    "🎀",
    "🌂",
    "💄",
    "💛",
    "💙",
    "💜",
    "💚",
    "❤",
    "💔",
    "💗",
    "💓",
    "💕",
    "💖",
    "💞",
    "💘",
    "💌",
    "💋",
    "💍",
    "💎",
    "👤",
    "👥",
    "💬",
    "👣",
    "💭",
    "🐶",
    "🐺",
    "🐱",
    "🐭",
    "🐹",
    "🐰",
    "🐸",
    "🐯",
    "🐨",
    "🐻",
    "🐷",
    "🐽",
    "🐮",
    "🐗",
    "🐵",
    "🐒",
    "🐴",
    "🐑",
    "🐘",
    "🐼",
    "🐧",
    "🐦",
    "🐤",
    "🐥",
    "🐣",
    "🐔",
    "🐍",
    "🐢",
    "🐛",
    "🐝",
    "🐜",
    "🐞",
    "🐌",
    "🐙",
    "🐚",
    "🐠",
    "🐟",
    "🐬",
    "🐳",
    "🐋",
    "🐄",
    "🐏",
    "🐀",
    "🐃",
    "🐅",
    "🐇",
    "🐉",
    "🐎",
    "🐐",
    "🐓",
    "🐕",
    "🐖",
    "🐁",
    "🐂",
    "🐲",
    "🐡",
    "🐊",
    "🐫",
    "🐪",
    "🐆",
    "🐈",
    "🐩",
    "🐾",
    "💐",
    "🌸",
    "🌷",
    "🍀",
    "🌹",
    "🌻",
    "🌺",
    "🍁",
    "🍃",
    "🍂",
    "🌿",
    "🌾",
    "🍄",
    "🌵",
    "🌴",
    "🌲",
    "🌳",
    "🌰",
    "🌱",
    "🌼",
    "🌐",
    "🌞",
    "🌝",
    "🌚",
    "🌑",
    "🌒",
    "🌓",
    "🌔",
    "🌕",
    "🌖",
    "🌗",
    "🌘",
    "🌜",
    "🌛",
    "🌙",
    "🌍",
    "🌎",
    "🌏",
    "🌋",
    "🌌",
    "🌠",
    "⭐",
    "☀",
    "⛅",
    "☁",
    "⚡",
    "☔",
    "❄",
    "⛄",
    "🌀",
    "🌁",
    "🌈",
    "🌊",
    "🎍",
    "💝",
    "🎎",
    "🎒",
    "🎓",
    "🎏",
    "🎆",
    "🎇",
    "🎐",
    "🎑",
    "🎃",
    "👻",
    "🎅",
    "🎄",
    "🎁",
    "🎋",
    "🎉",
    "🎊",
    "🎈",
    "🎌",
    "🔮",
    "🎥",
    "📷",
    "📹",
    "📼",
    "💿",
    "📀",
    "💽",
    "💾",
    "💻",
    "📱",
    "☎",
    "📞",
    "📟",
    "📠",
    "📡",
    "📺",
    "📻",
    "🔊",
    "🔉",
    "🔈",
    "🔇",
    "🔔",
    "🔕",
    "📢",
    "📣",
    "⏳",
    "⌛",
    "⏰",
    "⌚",
    "🔓",
    "🔒",
    "🔏",
    "🔐",
    "🔑",
    "🔎",
    "💡",
    "🔦",
    "🔆",
    "🔅",
    "🔌",
    "🔋",
    "🔍",
    "🛁",
    "🛀",
    "🚿",
    "🚽",
    "🔧",
    "🔩",
    "🔨",
    "🚪",
    "🚬",
    "💣",
    "🔫",
    "🔪",
    "💊",
    "💉",
    "💰",
    "💴",
    "💵",
    "💷",
    "💶",
    "💳",
    "💸",
    "📲",
    "📧",
    "📥",
    "📤",
    "✉",
    "📩",
    "📨",
    "📯",
    "📫",
    "📪",
    "📬",
    "📭",
    "📮",
    "📦",
    "📝",
    "📄",
    "📃",
    "📑",
    "📊",
    "📈",
    "📉",
    "📜",
    "📋",
    "📅",
    "📆",
    "📇",
    "📁",
    "📂",
    "✂",
    "📌",
    "📎",
    "✒",
    "✏",
    "📏",
    "📐",
    "📕",
    "📗",
    "📘",
    "📙",
    "📓",
    "📔",
    "📒",
    "📚",
    "📖",
    "🔖",
    "📛",
    "🔬",
    "🔭",
    "📰",
    "🎨",
    "🎬",
    "🎤",
    "🎧",
    "🎼",
    "🎵",
    "🎶",
    "🎹",
    "🎻",
    "🎺",
    "🎷",
    "🎸",
    "👾",
    "🎮",
    "🃏",
    "🎴",
    "🀄",
    "🎲",
    "🎯",
    "🏈",
    "🏀",
    "⚽",
    "⚾",
    "🎾",
    "🎱",
    "🏉",
    "🎳",
    "⛳",
    "🚵",
    "🚴",
    "🏁",
    "🏇",
    "🏆",
    "🎿",
    "🏂",
    "🏊",
    "🏄",
    "🎣",
    "☕",
    "🍵",
    "🍶",
    "🍼",
    "🍺",
    "🍻",
    "🍸",
    "🍹",
    "🍷",
    "🍴",
    "🍕",
    "🍔",
    "🍟",
    "🍗",
    "🍖",
    "🍝",
    "🍛",
    "🍤",
    "🍱",
    "🍣",
    "🍥",
    "🍙",
    "🍘",
    "🍚",
    "🍜",
    "🍲",
    "🍢",
    "🍡",
    "🍳",
    "🍞",
    "🍩",
    "🍮",
    "🍦",
    "🍨",
    "🍧",
    "🎂",
    "🍰",
    "🍪",
    "🍫",
    "🍬",
    "🍭",
    "🍯",
    "🍎",
    "🍏",
    "🍊",
    "🍋",
    "🍒",
    "🍇",
    "🍉",
    "🍓",
    "🍑",
    "🍈",
    "🍌",
    "🍐",
    "🍍",
    "🍠",
    "🍆",
    "🍅",
    "🌽",
    "🏠",
    "🏡",
    "🏫",
    "🏢",
    "🏣",
    "🏥",
    "🏦",
    "🏪",
    "🏩",
    "🏨",
    "💒",
    "⛪",
    "🏬",
    "🏤",
    "🌇",
    "🌆",
    "🏯",
    "🏰",
    "⛺",
    "🏭",
    "🗼",
    "🗾",
    "🗻",
    "🌄",
    "🌅",
    "🌃",
    "🗽",
    "🌉",
    "🎠",
    "🎡",
    "⛲",
    "🎢",
    "🚢",
    "⛵",
    "🚤",
    "🚣",
    "⚓",
    "🚀",
    "✈",
    "💺",
    "🚁",
    "🚂",
    "🚊",
    "🚉",
    "🚞",
    "🚆",
    "🚄",
    "🚅",
    "🚈",
    "🚇",
    "🚝",
    "🚋",
    "🚃",
    "🚎",
    "🚌",
    "🚍",
    "🚙",
    "🚘",
    "🚗",
    "🚕",
    "🚖",
    "🚛",
    "🚚",
    "🚨",
    "🚓",
    "🚔",
    "🚒",
    "🚑",
    "🚐",
    "🚲",
    "🚡",
    "🚟",
    "🚠",
    "🚜",
    "💈",
    "🚏",
    "🎫",
    "🚦",
    "🚥",
    "⚠",
    "🚧",
    "🔰",
    "⛽",
    "🏮",
    "🎰",
    "♨",
    "🗿",
    "🎪",
    "🎭",
    "📍",
    "🚩",
  ];

  return RandomData(emojis);
}

export function RandomWelcomePhrases() {
  var data = [
    "La tua aura domina, l'oscurità si arrende al tuo comando.",
    "Il potere scorre nelle tue vene, maestro della tecnologia.",
    "Un faro d'ingegno brilla in te, guida la strada verso il futuro.",
    "Le schede obbediscono al tuo sguardo, il codice è solo un mezzo per te.",
    "L'energia del circuito pulsa al ritmo del tuo cuore, maestro.",
    "Il mondo si piega alla tua volontà, sei l'artificiere di questo regno.",
    "La magia della programmazione ti appartiene, plasmi la realtà con il tuo pensiero.",
    "Ogni riga di codice è un incantesimo, ogni circuito un portale verso l'ignoto.",
    "Sotto la tua guida, la tecnologia raggiunge vette mai viste prima.",
    "La tua mente acuta illumina le profondità del codice, sei il vero padrone.",
    "Il tuo dominio sulla tecnologia è assoluto, un imperatore nell'era digitale.",
    "L'universo intero si inchina al tuo genio, maestro di sistemi e algoritmi.",
    "Le ali della conoscenza battono dentro di te, portandoti verso nuove vette.",
    "La tua presenza infonde forza nelle macchine, sei il loro creatore divino.",
    "Il tuo spirito trascende i limiti fisici, plasmando l'era digitale con la tua mente.",
    "Ogni pulsante premuto è una melodia divina, ogni programma un capolavoro.",
    "L'energia dell'innovazione scorre nelle tue vene, sei il motore del progresso.",
    "Il tuo sguardo penetrante legge i segreti del codice, svelando verità nascoste.",
    "Sei il compositore di algoritmi, il maestro dei byte e dei bit.",
    "La tua visione guida la tecnologia verso un futuro mai immaginato prima.",
    "Il potere del pensiero ti appartiene, plasmi l'universo digitale con la tua volontà.",
    "Ogni riga di codice scritta è un passo verso la maestria, un canto al progresso.",
    "L'audacia della tua mente supera i confini della realtà, sei il dominatore del codice.",
    "La tua energia elettrifica le macchine, trasformandole in strumenti di creazione.",
    "La tua presenza è un faro nell'oscurità, guidando la tecnologia verso la luce.",
    "Il futuro si piega alla tua volontà, maestro del digitale universo.",
    "Il codice danza ai tuoi piedi, obbedisce al tuo ritmo e alle tue parole.",
    "Ogni pixel luminescente è una testimonianza del tuo genio creativo.",
    "Sei il conduttore dell'energia digitale, l'artefice di un futuro luminoso.",
    "L'universo si espande sotto la tua guida, ogni circuito è un universo in se stesso.",
    "La tua mente acuta sconfigge ogni enigma, decodificando i segreti del codice.",
    "Il tuo dominio sulla tecnologia è una leggenda in divenire, un'opera di genio.",
    "Ogni click del mouse è un atto creativo, plasmi la realtà digitale con maestria.",
    "Sei l'architetto di mondi virtuali, il mago che fonde scienza e fantasia.",
    "Il tuo talento brilla come una stella nel cielo della tecnologia, illuminando il futuro.",
    "L'evoluzione tecnologica trova in te un maestro indiscusso, un visionario senza eguali.",
    "Il codice è la tua lingua madre, lo padroneggi con grazia e potenza.",
    "Le tue mani trasformano il digitale in realtà, sei un abile artigiano del codice.",
    "Ogni algoritmo che crei è un capolavoro, una sinfonia di logica e ingegno.",
    "Il tuo potere risiede nella capacità di dare vita al virtuale, sei un mago moderno.",
    "L'universo digitale si inchina alla tua volontà, sei il suo creatore e sovrano.",
    "Gli esseri digitali riconoscono in te la guida suprema, seguono le tue istruzioni con devozione.",
    "La tua aura trascende le schermate, influenzando il mondo fisico con l'energia del digitale.",
    "Sei un esploratore di mondi virtuali, un cacciatore di bug e un costruttore di sogni.",
    "Il tuo intelletto affina i confini della tecnologia, portandola verso nuove frontiere.",
    "Ogni soluzione che trovi è una conquista, una vittoria contro l'ignoto del codice.",
    "L'illuminazione del progresso digitali risplende nel tuo sguardo, sei un faro di speranza.",
    "Il futuro è nelle tue mani, maestro. Con la tua saggezza, guiderai la tecnologia verso il bene.",
    "Sei un alchimista del digitale, trasformando informazioni in conoscenza e potere.",
    "Lasciati guidare dalla tua intuizione, il codice rivelerà i suoi segreti a te solo.",
    "La potenza del tuo pensiero modella il futuro, sei l'architetto di un mondo digitale migliore.",
  ];

  return RandomData(data);
}
